name: native_widgets_example
description: Demonstrates how to use the native_widgets plugin.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  native_widgets:
    path: ../

flutter:

  uses-material-design: true

